### ISSUE TITLE
add LICENSE file

### ISSUE THREAD

**Issue by zpace** [syasini/AstroPaint#70]
Hello, I am one of your JOSS reviewers! (https://github.com/openjournals/joss-reviews/issues/2608)

I haven't been able to locate a plain-text LICENSE file in this repo. I see that an MIT license is listed in setup.py, so it would suffice to add the text from [here](https://opensource.org/licenses/MIT) into a new file called LICENSE in the top-level directory.

**Comment by syasini** [comment]
Hi Zach. Thanks for pointing that out! I don't know how I forgot to add the file to the repo. 

I just pushed a new commit to `develop` branch. Please check out the license file [here](https://github.com/syasini/AstroPaint/blob/develop/LICENSE) and if it's satisfactory I'll merge it to master and will close this issue.

**Comment by zpace** [comment]
Looks good to me :+1:

**Comment by syasini** [comment]
Awesome. Thanks!
