### ISSUE TITLE
painter.spray(..., parallel=True) fails ("unexpected keyword argument")

### ISSUE THREAD

**Issue by zpace** [syasini/AstroPaint#72]
JOSS reviewer here, again! (https://github.com/openjournals/joss-reviews/issues/2608)

I'm working your tutorial notebook, and I have run into a problem with `Painter.spray()`'s `parallel=True` argument. It seems that `parallel=True` is being passed to the function used as the `template` argument of the `Painter` instance. This is happening because `Painter.spray()` has no argument by that name. Eliminating this argument from the call to `Painter.spray()` yields the expected output.

I'm on version 0.1.1, which appears to be the most current. FWIW, this error also manifests with the public binder.

I *suspect* that the `n_cpus` argument has replaced `parallel`. If this is correct, please do update all public tutorials to reflect this.

**Comment by syasini** [comment]
Thanks for catching this bug @zpace. You're absolutely correct. `n_cpus` was suggested as a replacement for the `parallel` argument to give the user more control over parallelization, but after implementing the change we did not update the tutorial notebook. 

I just pushed a corrected version to `develop` which you can see here:   https://github.com/syasini/AstroPaint/blob/develop/tutorial.ipynb
  
(I really don't like GitHub's new notebook formatting; I really hope it's part of an A/B test and will be rolled out soon!)

I also fixed another error in a catalog file name at the very end. 

I'll check the other notebooks for similar errors and will keep you updated. Meanwhile, let me know if this looks good so I can merge it to master.

**Comment by zpace** [comment]
I think there's also a case of this in the README. Feel free to close this after checking the tutorial and other example notebooks.

**Comment by syasini** [comment]
You're absolutely right! I'll fix that one as well. Will close after all the corrections are implemented.

**Comment by syasini** [comment]
both instances of the `parallel=True` in the tutorial and README have been fixed. Thanks again for catching the mistakes! 

Closing this.
