### ISSUE TITLE
public documentation: Statement of need

### ISSUE THREAD

**Issue by zpace** [syasini/AstroPaint#73]
JOSS reviewer here! (https://github.com/openjournals/joss-reviews/issues/2608)

Please add a Statement of Need to the public-facing documentation of this repo. You could paraphrase the text already included in the JOSS manuscript submission; and then insert it into either your existing repo README, include it in the RTD homepage (see https://github.com/syasini/AstroPaint/issues/54), or preferably both!

**Comment by syasini** [comment]
For the moment I've added a new section `What is AstroPaint?` to the README file with the high-level overview of what the package is for. I will update this with a link to the JOSS paper after publication. I agree that this should definitely also go on the RTD homepage so I will keep that in mind.

**Comment by syasini** [comment]
I forgot to mention that the changes are applied to the `develop` branch as usual. I won't close this until I merge to `master`.

**Comment by syasini** [comment]
Closing this (see #54 ).
