### ISSUE TITLE
example name change

### ISSUE THREAD

**Issue by AshKelly** [syasini/AstroPaint#82]
I tried to follow some of the examples from the docs (https://astropaint.readthedocs.io/en/master/)

```catalog = Catalog("websky_lite_redshift")```

leads to an error that `websky_lite_redshift.csv` does not exist. I assume it has been replaced by `WebSky_2x2.csv` or `WebSky_lite.csv`.

**Comment by syasini** [comment]
Yes! That's exactly right. Thanks for noticing the mistake. I'll fix this momentarily.

**Comment by syasini** [comment]
The catalog's name has been fixed on the `develop` branch. You can check the [README](https://github.com/syasini/AstroPaint/tree/develop) and the [readthedocs](https://astropaint.readthedocs.io/en/develop/). 

I'll merge this into `master` as soon as you confirm.

**Comment by AshKelly** [comment]
That's great - thanks! Other libraries I'm involved with have abstracted their examples such that they also become tests. This is quite useful when the codebase is fluid and API's change often. 

I'm not suggesting you do this; however, just a thought going forward if the examples keep changing.

**Comment by syasini** [comment]
That's a great suggestion! I should definitely add some sort of integration testing to make sure the code can run simple examples on new releases. Thanks for pointing it out.
